config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  root "homes#top"
  resources :products do
    resources :product_techniques,only:[:create]
  end
  resources :users, only: [:show, :edit,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,length: {maximum: 50}
  validates :email ,presence: true
  validates :profile,length: {maximum: 250}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :products,dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    products_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    products_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    products_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_whether_correct_user, {only: [:edit,:update,:destroy]}
before_action :set_user,{only: [:show,:edit,:update,:destroy]}

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "ユーザー編集を完了しました"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "ユーザー #{@user.name}を削除しました。"
  end

  private
  def check_whether_correct_user #他ユーザーの情報を編集・削除できないように制限（管理者ユーザーは覗く）
    @user = User.find(params[:id])
    unless current_user.admin == true || current_user.id == @user.id
    redirect_to user_path(current_user),notice: "編集・削除権限がありません"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email,:name,:profile)
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<% provide(:title,"作品の編集") %>

<div class="container">
  <h2 class="title text-center mt-5 mb-3">ユーザーの編集</h2>
  <% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @user.errors.full_messages.each do |message
  |%>
      <li><%=message%> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_with model: @user,local: true do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:"form-control",required: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, autofocus: true, class:"form-control",required: true %>
  </div>

  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_area :profile, class:"form-control",style: "width:100%;min-height:150px;"%>
  </div>

  <div class="actions">
    <%= f.submit "編集を確定する", class:"form-control submit-button"  %>
  </div>
  <% end %>


  <div class="actions destroy-user text-center">
    <%= link_to  "ユーザーを削除する", user_path(@user),class: "my-5 text-center danger",method: :delete,data: {confirm: "削除するユーザーの投稿した作品も全て削除されます。\n本当にユーザー（#{@user.name}）を削除しますか？"} %>
  </div>

</div>

app/views/users/show.html.erb
<%= provide(:title,"#{@user.name}") %>

<main>
  <div class="container">
    <h3 class="title text-center my-5">マイページ </h3>
    <h4 class="title text-center mb-5">
      <%= @user.name %>の作品一覧
    </h4>

    <div class="products-list">
      <% @user.products.each do |user_product| %>
      <div class="card">
        <% if user_product.image.present? %>
        <%= cl_image_tag(user_product.image,class:"product-image") %>
        <% else %>
        <%= cl_image_tag "Noimage.png", class:"product-image" %>
        <% end %>

        <div class="card-body text-center">
          <h5 class="card-title"><%= user_product.name %></h5>
          <p class="card-text text-left"><%= truncate(user_product.description,length: 13,separator: /。/)%> </p>
          <%= link_to  "この作品を見る", product_path(user_product), class:"product"%>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</main>

<%= stylesheet_pack_tag "users/show"%>