config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  root "homes#top"
  resources :products do
    resources :product_techniques,only:[:create]
  end
  resources :users, only: [:show, :edit,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true,length: {maximum: 50}
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/
  validates :description,length: {maximum: 250}
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :product_techniques, dependent: :destroy
  has_many :techniques, through: :product_techniques


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_whether_correct_user,{only:[:edit,:update,:destroy]}
  before_action :set_product,only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @technique = Technique.all
  end

  def create
    if create_new_product
      redirect_to products_path, notice: '登録しました'
    else
      @technique = Technique.all
      render :new
    end
  end

  def show
  end

  def edit
    @technique = Technique.all
  end

  def update
    if update_product
      redirect_to product_path(@product), notice: '編集完了しました'
    else
      @technique = Technique.all
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: '削除しました'
  end



  private

  def check_whether_correct_user #他ユーザーのproductsを編集・削除できないように制限（管理者ユーザーは除く）
    @product = Product.find(params[:id])
    unless current_user.admin == true || current_user.id == @product.user_id
    redirect_to product_path(@product),notice: "編集・削除権限がありません"
    end

  end

  def set_product
    @product = Product.find(params[:id])
  end


  def create_new_product
    @product = current_user.products.new(product_params)
    used_technique_ids[:techniques].each do |used_technique_id|
      @product.product_techniques.build(technique_id: used_technique_id)
    end
    @product.save
  end

  def update_product
      @product.update(product_params)
      @product.product_techniques.delete_all
      used_technique_ids[:techniques].each do |used_technique_id|
        @product.product_techniques.new(technique_id: used_technique_id)
      end
      @product.save
    end
end

def product_params
  params
  .require(:product)
  .permit(:name,:image, :image_cache, :remove_image, :url, :description)
end

def used_technique_ids
  params.require(:product).permit(techniques: [])
end

app/helpers/products_helper.rb
module ProductsHelper


end

app/views/products/edit.html.erb
<% provide(:title,"作品の編集") %>

<div class="container">
  <h2 class="title text-center mt-5 mb-3">作品の編集</h2>
  <% if @product.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @product.errors.full_messages.each do |message|%>
      <li><%=message%> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_with model: @product,local: true do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:"form-control",required: true %>
  </div>

  <%
    whether_params_have_product = params[:product].present? ? params[:product][:techniques] : @product.technique_ids
  %>
  <div class="field check-boxes">
    <%= f.label :techniques %><br />
    <%= f.collection_check_boxes(:techniques,@technique,:id,:technique,include_hidden: false,checked: whether_params_have_product, required: true) do |b|%>
    <%= b.label {b.check_box(class: "technique") + b.text }%>
    <% end %>
  </div>


  <div class="field">
    <%= f.label :image %><br />
    <%= image_tag(@product.image_url) if @product.image? %>
    <%= f.file_field :image, class:"form-control" %>
    <%= f.hidden_field :image_cache %>
    <label>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, class:"form-control",required: true %>
    <label>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class:"form-control",style: "width:100%;min-height:150px;"%>
  </div>

  <div class="actions">
    <%= f.submit "編集を確定する", class:"form-control submit-button"  %>
  </div>
  <% end %>
<div class="actions text-center">
  <%= link_to  "この作品を削除する", product_path(@product), class:"actions danger",method: :delete, data: { confirm:"本当に削除しますか？" } %>
</div>

</div>

<%= javascript_pack_tag "products/edit" %>

app/views/products/index.html.erb
<% provide(:title, "作品一覧")%>
<main>
  <h3 class="title text-center my-5">作品一覧</h3>
  <div class="container">
    <div id='vue-template'></div>

    <%
=begin
%>
    <div class="sorts-list d-flex justify-content-around mb-4">
      <a href="#">新着投稿</a>
      <a href="#">人気の投稿</a>
      <a href="#">言語で調べる</a>

    </div>
    <div class="products-list">
      <% @products.each do |product|%>
      <div class="card">
        <% if product.image.present? %>
        <%= cl_image_tag(product.image,class:"product-image") %>
        <% else %>
        <%= cl_image_tag "Noimage.png", class:"product-image" %>
        <% end %>

        <div class="card-body text-center">
          <h5 class="card-title"><%=product.name%></h5>
          <p class="card-text text-left"><%= truncate(product.description,length: 13,separator: /。/)%> </p>
          <%= link_to  "この作品を見る", product_path(product), class:"product"%>
        </div>
      </div>
      <% end %>
    </div>
    <%
=end
%>
  </div>
</main>

<%= stylesheet_pack_tag "products/index"%>
<%= javascript_pack_tag "hello_vue" %>
<%= stylesheet_pack_tag "hello_vue"%>

<%= content_tag :div,
   id: "productsIndex",
   data: {
    products:@products
   }.to_json do %>
<% end %>

app/views/products/new.html.erb
<% provide(:title,"作品の登録") %>

<div class="container">
  <h2 class="title text-center mt-5 mb-3">作品の登録</h2>
  <% if @product.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @product.errors.full_messages.each do |message
  |%>
      <li><%=message%> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_with model: @product,local: true do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:"form-control",required: true %>
  </div>

  <%
    whether_params_have_product = params[:product].present? ? params[:product][:techniques] : @product.technique_ids
  %>
  
  <div class="field check-boxes">
    <%= f.label :techniques %><br />
    <%= f.collection_check_boxes(:techniques,@technique,:id,:technique,include_hidden: false,checked: whether_params_have_product,required: true) do |b|%>
    <%= b.label {b.check_box(class: "technique") + b.text }%>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= image_tag(@product.image_url) if @product.image?%>
    <%= f.file_field :image, class:"form-control" %>
    <%= f.hidden_field :image_cache %>
    <label>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, class:"form-control" ,required: true %>
    <label>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class:"form-control",style: "width:100%;min-height:150px;"%>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class:"form-control submit-button"  %>
  </div>
  <% end %>
  <div class="text-center mt-3">
  </div>

</div>

<%= stylesheet_pack_tag "products/new"%>
<%= javascript_pack_tag "products/new" %>

app/views/products/show.html.erb
<% provide(:title ,"作品詳細")%>
<%= stylesheet_pack_tag "products/show"%>
<div class="container">
  <div class="card my-5">
    <% if @product.image.present? %>
    <%= cl_image_tag @product.image.to_s, class:"product-image" %>
    <% else %>
    <%= cl_image_tag "Noimage.png",class:"product-image" %>
    <% end %>
    <div class="card-body text-center">
      <h3 class="card-title mb-5"><%=@product.name%></h3>
      <p class="card-text text-center"><%= @product.description%> </p>
      <div class="product-actions">
        <%= link_to  "この作品を見に行く", "#{@product.url}",class:"text-center mb-1",target: "_blank" %>

        <% if current_user.admin == true || @product.user_id == current_user.id %>
          <%= link_to  "この作品を編集する", edit_product_path, class:"text-center mb-1" %>
        <% end %>

      </div>
    </div>
  </div>
</div>