config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  root "homes#top"
  resources :products do
    resources :product_techniques,only:[:create]
  end
  resources :users, only: [:show, :edit,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
<p class="text-center">@Port-Share All Rights Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg d-flex fixed-top bg-white">
  <div class="container">
    <h1 class="navbar-brand">Port-Share</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <nav class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav d-flex m-0">

        <% if current_user %>
        <% if current_page?(user_path(current_user)) %>
        <li class="nav-item">
          <%= link_to edit_user_path(current_user) do %>
          <i class="fas fa-cog"></i>
          <span>ユーザー編集</span>
          <% end %>
        </li>
        <% end %>

        <% unless current_page?(user_path(current_user)) %>
        <li class="nav-item">
          <%= link_to user_path(current_user) do %>
          <i class="fas fa-user"></i>
          <span>マイページ</span>
          <% end %>
        </li>
        <% end %>

        <li class="nav-item"><%= link_to products_path do %>
          <i class="fas fa-list-alt"></i>
          <span>作品一覧</span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to new_product_path do %>
          <i class="fas fa-plus"></i>
          <span>投稿する</span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete do%>
          <i class="fas fa-sign-out-alt"></i>
          <span>ログアウト</span>
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
          <i class="fas fa-user-plus"></i>
          <span>新規登録</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path,class:"Log-in" do %>
          <i class="fas fa-sign-in-alt"></i>
          <span>ログイン</span>
          <% end %>
        </li>
      </ul>

      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield :title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

</head>
<%= stylesheet_pack_tag 'application', media: 'all'%>
<%= javascript_pack_tag 'application'%>

<body>
  <%= render  "layouts/header" %>

  <% if flash.present? %>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
  <% end %>
  <% end %>

  <%= yield %>

  <%= render "layouts/footer" %>
</body>

</html>